###
POST http://localhost:4001/auth/login
Content-Type: application/json
Authorization: Basic bXV0eWEtYnJva2VyMTpwYXNzMTIz

###
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11dHlhLWJyb2tlcjEiLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzUyNTU4NTI2LCJleHAiOjE3NTI1NTk3MjZ9.CR6b2JXE2-6z8lhSJUYwgwh5uBRG9Q9egXEfdayMIl4
POST http://localhost:4001/auth/refresh
Authorization: Bearer {{refreshToken}}

###
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11dHlhLWJyb2tlcjEiLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NTQyODYzMzksImV4cCI6MTc1NDI4NzIzOX0.Yy6q_HBsuQYEZ2YHGk-RzYMaKVNMPT9U8PKi6kQvLB8
GET http://localhost:4001/user/info
Authorization: Bearer {{accessToken}}

###
GET http://localhost:4001/reference/clients
Authorization: Bearer {{accessToken}}

###
GET http://localhost:4001/reports/summary?from_date=01/01/2025&to_date=07/08/2025&client_code=479354463000
Authorization: Bearer {{accessToken}}


###
POST http://localhost:4001/reports/pro-info
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
  {
    "val_type"     : "airwaybill",
    "val_list"     : "AAGJ003921",
    "generate_type": "PRO"
  }
]

###
GET http://localhost:4001/reference/check/pro-exist?val_type=pronumber&value=RVM2500013T
Authorization: Bearer {{accessToken}}

###
GET http://localhost:4001/reference/transactions/details?value=RVM2500013T
Authorization: Bearer {{accessToken}}